### PR TITLE
Add Docker image

### PR DESCRIPTION
**Pull request by hwittenborn**

### CODE REVIEW

**Review by ryleu — CHANGES_REQUESTED** [review]
config variables should be supplied by the user of the dockerfile, not included in the dockerfile. they are config variables, after all

**Comment by hwittenborn** [comment]
Those are just default values - if the user wants to override them at runtime they're still able to. I just thought it'd make it a simpler for your use case.

**Comment by ryleu** [comment]
defaults that work for very few people shouldn't be defaults. i would prefer that users read the docs (that i'll write eventually<sup>tm</sup>) than come to me with questions about why it's the wrong menu

**Comment by ryleu** [comment]
looks good, merged 🫡

**Pull request merged**
